//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myimage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string Image1 { get; set; }
        public string Pr_size { get; set; }
        public Nullable<decimal> Pr_price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> T_price { get; set; }
        public string Email { get; set; }
    }
}
